LEMONSTATUS(1)

# NAME

lemonstatus - generate lemonbar content

# SYNOPSIS

*lemonstatus* | lemonbar -p

# DESCRIPTION

*lemonstatus* is developed for use with OpenBSD and cwm. It depends on++
*apm* and *kqueue*, and displays group numbers from \_NET_CURRENT_DESKTOP++
and \_NET_NUMBER_OF_DESKTOPS X properties.

# CONFIGURATION

*lemonstatus* is configured through config.h file, 'cause it doesn't suck.

# SEE ALSO

lemonbar(1)

# AUTHOR

peajack <peajackboatan@ya.ru>
